CRUDFisi/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDFisi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FisiEntities : DbContext
    {
        public FisiEntities()
            : base("name=FisiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumnos> alumnos { get; set; }
    }
}

CRUDFisi/Models/Model1.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\User\source\repos\CRUDFisi\CRUDFisi\Models\Model1.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

CRUDFisi/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

CRUDFisi/Models/ViewModels/AlumnosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CRUDFisi.Models.ViewModels
{
    public class AlumnosViewModel
    {
        
        public int Id { get; set; }
        [Required]
        [StringLength(20)]
        [Display(Name ="Nombre")]
        public string Nombre { get; set; }
        [Required]
        [StringLength(20)]
        [Display(Name ="Apellido")]
        public string Apellido { get; set; }
        [Required]
        [StringLength(8)]
        [Display(Name ="Código")]
        public string Codigo { get; set; }

    }
}

CRUDFisi/Models/ViewModels/ListAlumnosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CRUDFisi.Models.ViewModels
{
    public class ListAlumnosViewModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Codigo { get; set; }
    }
}

CRUDFisi/Models/alumnos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDFisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string codigo { get; set; }
    }
}

CRUDFisi/Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRUDFisi.Models;
using CRUDFisi.Models.ViewModels;

namespace CRUDFisi.Controllers
{
    public class AlumnosController : Controller
    {
        // GET: Alumnos
        public ActionResult Index()
        {

            List<ListAlumnosViewModel> lst;
            using(FisiEntities db = new FisiEntities())
            {
                lst = (from p in db.alumnos
                          select new ListAlumnosViewModel
                          {
                              Id = p.id,
                              Nombre = p.nombre,
                              Apellido = p.apellido,
                              Codigo = p.codigo,

                          }).ToList();
            }

            return View(lst);
        }
        
        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(AlumnosViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    using(FisiEntities db = new FisiEntities())
                    {
                        var oAlumnos = new alumnos();
                        oAlumnos.nombre = model.Nombre;
                        oAlumnos.apellido = model.Apellido;
                        oAlumnos.codigo = model.Codigo;

                        db.alumnos.Add(oAlumnos);
                        db.SaveChanges();
                    }

                    return Redirect("~/Alumnos/");

                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            AlumnosViewModel model = new AlumnosViewModel();
            using(FisiEntities db = new FisiEntities())
            {
                var oAlumnos = db.alumnos.Find(id);
                model.Nombre = oAlumnos.nombre;
                model.Apellido = oAlumnos.apellido;
                model.Codigo = oAlumnos.codigo;
                model.Id = oAlumnos.id;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(AlumnosViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (FisiEntities db = new FisiEntities())
                    {
                        var oAlumnos = db.alumnos.Find(model.Id);
                        oAlumnos.nombre = model.Nombre;
                        oAlumnos.apellido = model.Apellido;
                        oAlumnos.codigo = model.Codigo;

                        db.Entry(oAlumnos).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/Alumnos/");

                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            AlumnosViewModel model = new AlumnosViewModel();
            using (FisiEntities db = new FisiEntities())
            {
                var oAlumnos = db.alumnos.Find(id);
                db.alumnos.Remove(oAlumnos);
                db.SaveChanges();
            }

            return Redirect("~/Alumnos/");
        }
    }
}

CRUDFisi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUDFisi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CRUDFisi/Views/Alumnos/Editar.cshtml
@model CRUDFisi.Models.ViewModels.AlumnosViewModel

@{
    ViewBag.Title = "Editar datos del alumno nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Alumnos", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d =>d.Id)
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Apellido)
                @Html.TextBoxFor(d => d.Apellido, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Apellido, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Codigo)
                @Html.TextBoxFor(d => d.Codigo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Codigo, null, new { @class = "red" })
            </div>
            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}

CRUDFisi/Views/Alumnos/Index.cshtml
@model List<CRUDFisi.Models.ViewModels.ListAlumnosViewModel>
@{
    ViewBag.Title = "Datos del alumno";
}

<h2>@ViewBag.Title</h2>

<div class="row" style="text-align:right;padding:5px;">
    <a href="~/Alumnos/Nuevo" class="btn btn-primary">Nuevo</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Código</th>
            </tr>
            @foreach (var elemento in Model)
            {
                <tr>
                    <td>@elemento.Id</td>
                    <td>@elemento.Nombre</td>
                    <td>@elemento.Apellido</td>
                    <td>@elemento.Codigo</td>
                    <td>
                        <a class="btn btn-default" href="~/Alumnos/Editar/@elemento.Id">Editar</a>
                        <a class="btn btn-danger" href="~/Alumnos/Eliminar/@elemento.Id">Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

CRUDFisi/Views/Alumnos/Nuevo.cshtml
@model CRUDFisi.Models.ViewModels.AlumnosViewModel

@{
    ViewBag.Title = "Datos del alumno nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "Alumnos", FormMethod.Post))
{
<div class="row">
    <div class="col-md-12">
        <div>
            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.Apellido)
            @Html.TextBoxFor(d => d.Apellido, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Apellido, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.Codigo)
            @Html.TextBoxFor(d => d.Codigo, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Codigo, null, new { @class = "red" })
        </div>
            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
    </div>
</div>
}

CRUDFisi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CRUDFisi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CRUDFisi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CRUDFisi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>